export const ROUTES = {
  HOME: '/',
  CHECKOUT: '/checkout',
  CHECKOUT_DIGITAL: '/checkout/digital',
  GUEST_CHECKOUT: '/checkout/guest',
  PROFILE: '/profile',
  CHANGE_PASSWORD: '/change-password',
  ORDERS: '/orders',
  REFUNDS: '/refunds',
  HELP: '/help',
  LOGOUT: '/logout',
  OFFERS: '/offers',
  ORDER_RECEIVED: '/order-received',
  PRODUCT: '/products',
  ORDER: '/order',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  CONTACT: '/contact',
  SHOPS: '/',
  DOWNLOADS: '/downloads',
  AUTHORS: '/authors',
  MANUFACTURERS: '/manufacturers',
  SEARCH: '/search',
};
