export const API_ENDPOINTS = {
  PRODUCTS: '/products.php',
  ORDERS: '/orders.php',
  CREATE_ORDER: '/create-order.php',
  USERS_ME: '/me.php',
  SETTINGS: '/settings.php',
  USERS_LOGIN: '/token.php',
  USERS_CHANGE_PASSWORD: '/change-password.php',
  USERS_CONTACT_US: '/contact.php',
  UPDATE_CONTACT: '/update-user.php',
  USERS_REGISTER: '/register.php',
  USERS_FORGOT_PASSWORD: '/forget-password.php',
  VALIDATE_STOCK: 'stock-validation.php',

  PRODUCTS_POPULAR: '/popular-products',
  CATEGORIES: '/categories',
  TYPES: '/types.php',
  TAGS: '/tags',
  SHOPS: '/shops',
  AUTHORS: '/authors',
  AUTHORS_TOP: '/top-authors',
  MANUFACTURERS: '/manufacturers',
  MANUFACTURERS_TOP: '/top-manufacturers',
  COUPONS: '/coupons',
  COUPONS_VERIFY: '/coupons/verify',
  ORDERS_STATUS: '/order-status',
  ORDERS_REFUNDS: '/refunds',
  ORDERS_CHECKOUT_VERIFY: '/orders/checkout/verify',
  ORDERS_DOWNLOADS: '/downloads',
  GENERATE_DOWNLOADABLE_PRODUCT_LINK: '/downloads/digital_file',
  USERS: '/users',
  USERS_ADDRESS: '/address',
  USERS_VERIFY_FORGOT_PASSWORD_TOKEN: '/verify-forget-password-token',
  USERS_RESET_PASSWORD: '/reset-password',
  USERS_LOGOUT: '/logout',
  USERS_SUBSCRIBE_TO_NEWSLETTER: '/subscribe-to-newsletter',
  UPLOADS: '/attachments',
};
